import "./globals.css";

export const metadata = {
  title: "Space Jam",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
